### ISSUE TITLE
Post ownership transfer cleanup

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/CatBoost.jl#19]
Some of the README badges  are broken, in particular the docs one.

**Comment by ararslan** [comment]
Relatedly, can you add some Beacon folks as administrators on this repository if you haven't already? Eric and McCoy had administrative access prior to the transfer. I'd recommend at least them and maybe myself for redundancy but not necessary.

**Comment by ericphanson** [comment]
@ablaom did add me as admin right after the transfer

**Comment by ararslan** [comment]
Perfect!

**Comment by ablaom** [comment]
> @ablaom did add me as admin right after the transfer

No that appeared to happen automatically. You should be able to add the others yourself, no?

**Comment by ablaom** [comment]
Okay, it looks like that's done.

**Comment by ericphanson** [comment]
Closed by #24 I believe
